# Generated by Django 4.2.2 on 2023-06-11 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=50)),
                ('nameRef', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('nameRef', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=10)),
                ('iconAbsolutePath', models.URLField()),
                ('name', models.CharField(max_length=50, unique=True)),
                ('nameRef', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpellSpeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('nameRef', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='vocabTermLOR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('nameRef', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associatedCards', models.JSONField(default=list)),
                ('associatedCardRefs', models.JSONField(default=list)),
                ('assets', models.JSONField(default=list)),
                ('regions', models.JSONField(default=list)),
                ('attack', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=255)),
                ('descriptionRaw', models.CharField(max_length=255)),
                ('levelupDescription', models.CharField(max_length=255)),
                ('levelupDescriptionRaw', models.CharField(max_length=255)),
                ('flavorText', models.TextField()),
                ('artistName', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('cardCode', models.CharField(max_length=10, unique=True)),
                ('keywords', models.JSONField(default=list)),
                ('keywordRefs', models.JSONField(default=list)),
                ('spellSpeed', models.CharField(max_length=50)),
                ('rarity', models.CharField(max_length=50)),
                ('subtypes', models.JSONField(default=list)),
                ('supertype', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('collectible', models.BooleanField(default=False)),
                ('set', models.CharField(max_length=50)),
                ('formats', models.JSONField(default=list)),
                ('formatRefs', models.JSONField(default=list)),
                ('rarityRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rarity')),
                ('regionsRefs', models.ManyToManyField(to='api.region')),
                ('spellSpeedRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.spellspeed')),
            ],
        ),
    ]
